### ISSUE TITLE
[Feature Request] Anime Support From Aniyomi Fork

### ISSUE THREAD

**Issue by AdmnJ** [AriaMoradi/Tachidesk#365]
---

I was wording how difficult it would be to build in anime support utilizing the aniyomi fork of tachiyomi https://github.com/jmir1/aniyomi . I know it likely wouldn't be a drop in upgrade but considering it was forked from the same project I thought it might be worth discussing it.

Adding anime support definitely would add to the uses of the server, making it a one stop shop for a lot of media server needs.

**Comment by Syer10** [comment]
Anime was supported for a while, but it ended up being a chore to keep working since it wasnt that well developed. Mostly being a copy of the manga support. It also wasnt implemented in most the available clients like JUI because the developers were not interested in it. In the WebUI client it barely worked because it was browser based and browsers have strict implementation details regarding video playback.

It was eventually removed because of these issues in v0.6.0, but if someone can make a good implementation of it it could be re-added.

**Comment by AdmnJ** [comment]
> Anime was supported for a while, but it ended up being a chore to keep working since it wasnt that well developed. Mostly being a copy of the manga support. It also wasnt implemented in most the available clients like JUI because the developers were not interested in it. In the WebUI client it barely worked because it was browser based and browsers have strict implementation details regarding video playback.
> 
> 
> 
> It was eventually removed because of these issues in v0.6.0, but if someone can make a good implementation of it it could be re-added. 

Makes sense, Is there an archive of when it was implemented so I can see how it worked?

**Comment by Syer10** [comment]
Its available in the git history, here is the last revision before it was removed https://github.com/Suwayomi/Tachidesk-Server/tree/c1e6f4c26eb75d7ca9a6818bfb538ebee8547a14/server/src/main/kotlin/suwayomi/tachidesk/anime

**Comment by AriaMoradi** [comment]
Supproting Aniyomi is "planned" as a fork of Tachidesk named "Anidesk". As mentioned by Syer, having the support for anime in Tachidesk is too much of a chore and not needed added complexity. We could very well move AndroidCompat into a separate project and have both projects depend on it.
