### ISSUE TITLE
[Feature Request] <Removing Manga Directly From Library>

### ISSUE THREAD

**Issue by johnranyer13** [AriaMoradi/Tachidesk#386]
## What feature should be added to Tachidesk?
Removing a saved manga directly from library interface without entering the specific manga just to remove it.
--Multiple removing of manga directly from library interface-- By multiple selection.

##  Why/Project's Benefit/Existing Problem
Easier way to cleanup a library.
Can't Remove a manga with its missing extension especially if the backup files comes from tachiyomi android.
Can't Remove a manga when trying to open it only white screen appears.

Tachidesk-Server Version: Stable v0.6.3-r1112-windows-x64

![Screenshot_1](https://user-images.githubusercontent.com/64979038/184523039-832a739b-ef65-4976-b83d-5bfac2eee26c.png)

## ISSUE
> **`Missing Extension`**
![missing extension](https://user-images.githubusercontent.com/64979038/184522973-1b2a6e08-f8e4-4db8-8622-8f6fde07decf.gif)

> **`Broken Manga`**
![broken manga](https://user-images.githubusercontent.com/64979038/184522981-13f3e9d6-c6be-44c5-a41c-698f871b6cac.gif)

**Comment by PacaPop** [comment]
How can we remove the buggy mangas now? Without this feature it's impossible. I've got a lot of titles added to my library and when i click them i get the white screen always.

**Comment by schroda** [comment]
the bug (whitescreen) is an issue of the webUI, which got fixed in one of the webUI preview versions https://github.com/Suwayomi/Tachidesk-WebUI-preview (or https://tachidesk-webui-preview.github.io/ - works with localhost server address) (you might also need the server preview version, but not sure https://github.com/Suwayomi/Tachidesk-Server-preview)
