### ISSUE TITLE
[Feature Request] way to select/multi-select like in tachiyomi to either mark as read, delete manga, and remove reading history

### ISSUE THREAD

**Issue by ChillyCrimson45** [AriaMoradi/Tachidesk#404]
we need it because my phone broke and i can't access the app to make a backup and its hard to like manually mark the chapters in updates or just the library to just be marked read i recommend some sort of keybind and mouse1 for convenience ty

**Comment by Robonau** [comment]
select/multi-select is blocked by lack of batch endpoints

mark as read, delete manga, and remove reading history on single manga from the library view could be done but would be an issue for the UIs not server

**Comment by ChillyCrimson45** [comment]
if it can be at least done in the library then its great

**Comment by Sirver51** [comment]
@Robonau Is batch support on the server required for this? I had a large number of entries to add from my local source to my library (for access via the extension) and I ended up writing a small script to just send the appropriate API request for each item. I haven't looked at the code for the WebUI yet, but I assume something similar could be done without much fuss. My experience with Electron (and JS in general) is almost non-existent, but I could give it a shot myself if you think the method is viable.

**Comment by martinek** [comment]
Batch API for enqueuing downloads was added yesterday. I presume other batch endpoints will be comming soon-ish. I wanted to finish WebUI support for batch downloads and then have a look at other actions.

I presume you want all of these from library? Since you can already mark all chapters as read and delete manga from manga detail. I'm not sure what "remove reading history" means exactly.

**Comment by Seiris21** [comment]
I guess this is sort of tangentially related, so commenting here instead of filing a new request. 

If there was a way to select/multi-select series from library, it could make categorizing series less tedious (if this feature could be added as well). As far as I can tell, the current workflow is: Click Series > Set Category > Back to Library > Repeat. Having multi-select in library would help improve ux I think.

**Comment by Clover-Zero** [comment]
> If there was a way to select/multi-select series from library, it could make categorizing series less tedious (if this feature could be added as well). As far as I can tell, the current workflow is: Click Series > Set Category > Back to Library > Repeat. Having multi-select in library would help improve ux I think.

I second this. Please. I just want a way to select multiple series for easier categorization, something Tachiyomi can do. Or do I need to fill a new request?

**Comment by Syer10** [comment]
Completed
