### ISSUE TITLE
[Feature Request] Tachidesk Server for arm Linux

### ISSUE THREAD

**Issue by anyoneyun** [AriaMoradi/Tachidesk#485]
Hi, I couldn't find any version of Tachidesk Server for arm on Linux. Are you planning to release a version that supports it? Thanks!

**Comment by AriaMoradi** [comment]
Tachidesk runs on java which means in runs on any platform that is supported by java, just install a JRE (OpenJDK preferred) and run it using `.sh` scripts from https://github.com/Suwayomi/Tachidesk-Server/tree/master/scripts/resources

We haven't released an arm package because there isn't much demand for it.
