### ISSUE TITLE
[Feature Request] add auto download

### ISSUE THREAD

**Issue by BaccanoMob** [AriaMoradi/Tachidesk#628]
As name suggests, when you only update the library new chapters are pushed to download. And this setting to be included in the config file.

This will be helpful if you have a big library. I know we can click the chapters in updates menu one by one, but doing everything in a single click would be great.

**Comment by schroda** [comment]
the latest preview version has a new setting in the config file to auto download new chapters (https://github.com/Suwayomi/Tachidesk-preview/releases/latest)

**Comment by AngelaDMerkel** [comment]
This issue is closed, but I don't think it should be, at least not in the docker image. Having to attach to the container and install a text editor, to then edit a config several layers deep is not really very intuitive and impractical for some (most) users. I understand it is a server installation, but the application would be much more polished if there was a toggle or the config file was exposed on the host filesystem.

**Comment by Syer10** [comment]
... we have environment variables for all settings. Please read the docker image README.

**Comment by Robonau** [comment]
also the webui (preview channel) has settings for all (or most) of the server configs
including auto downloads
