### ISSUE TITLE
[Bug] Some sources cause mangas to lose their "read" chapter marks and reupdates all chapters as if mangas were just added to library.

### ISSUE THREAD

**Issue by domppa1000** [AriaMoradi/Tachidesk#693]
-Summary-
I am not sure if this problem can be fixed from Tachyomi side, Tachidesk side or from the Source site's side, but with some sources this happens:
Every 5-10 days Tachidesk loses some of the manga info (that are in my library) from the source and reapplies them as new contents.
This includes reupdating all of the manga episodes to the "update" section and the app forgetting all of the "read" chapters of specific sources.
The sources that l have seen doing this: Asurescans (https://asuracomics.gg/) and Mangademon (https://manga-demon.org/)
The only way that l can circumvent this problem is to change sources to other sites.

## Device information
- Tachidesk version: v0.7.0-r1197
- Server Operating System: Windows 10 Pro x64
- Server Desktop Environment: N/A
- Server JVM version: Java 8 Update 351 (build 1.8.0_351-b10)
- Client Operating System: Same as above Server Operating System
- Client Web Browser: Google Chrome  116.0.5845.188

## Steps to reproduce
1. First Step
Install Asure Scans or Manga Demon extension.
2. Second Step
Add a manga from these sites to your library.
3. Third Step
Mark the chapters as read and while you are at it check the "Updates" section for current date.
4. Fourth Step
Wait 5-10 days and check if chapters have unmarked from read to unread and check if the chapters have reuploaded in the "Updates" section.

### Expected behavior
Chapters should stay as read and not change back and all of the chapters should not reappear as new in the "Updates" section.

### Actual behavior
Chapters change back to unread and all of the chapters reappear as new in the "Updates" section as if you just added the manga into your library.

## Other details
The sources that l have seen doing this: Asurescans (https://asuracomics.gg/) and Mangademon (https://manga-demon.org/)
The only way that l can circumvent this problem is to change sources to other sites.

**Comment by domppa1000** [comment]
Update to this:
Tested Tachiyomi with these sources for 2 weeks and the problem has not occurred with the app, so it seems to be Tachidesk specific. 
It could still be a problem with how the app doesn't recognize, if the sources change their links or just has some conflict with these websites. Or the sites themselves have some kind of a problem.

**Comment by Underestimated** [comment]
I’ll add to this, it seems to be with sources like Asurascans that occasionally change their chapter id’s and domain name, the server sees the chapters as whole new chapters and resets those to unread (while removing other chapters because the old urls are gone)



 I’ve worked around this by having a third party tool occasionally ping the server api for a list of all asurascan chapters and their status, and store the highest read number in a separate data table, then when it runs again start by marking all chapters up to the latest read one as read before running again. 

That’s obviously not ideal, the issue lies with how tachidesk sees and recognises the data, and stores it long term.

off topic but:
This also ties into another issue that is probably on a roadmap somewhere, works are only stored as single sources, and reading progress doesn’t sync across different scanlation groups. That particular issue probably won’t resolve without a rewrite of how tachidesk treats works though, as right now everything is based on the source. 
Adding multiple sources for a work will probably require a complete rethink on how works are recognised and stored, and finding some way of divorcing the work from the source completely, allowing for multiple sources to be attached and a preferred source/scanlation subgroup to be selected.

**Comment by cyntalan** [comment]
Another interesting facet I've found with this same issue is if chapters are downloaded, Tachidesk no longer recognizes them as downloaded and re-downloading does so the long way. I've had chapters downloaded where it forgets sometimes but re-downloading makes Tachidesk go "oh, it's already all here" and flags it as downloaded real quick, but now it's re-downloading them entirely and overwriting what is there already. Wonder if there can be a file comparison check in these instances to confirm the contents are the same before re-downloading? If the issue of unread flagging is resolved, though, this too might resolve itself.

**Comment by Marnalas** [comment]
Still happening with the Asura Scans extension (server version : v0.7.0 stable)

**Comment by Syer10** [comment]
This is fixed in the preview version of Tachidesk
