### ISSUE TITLE
[Question] How do I shutdown the server besides going into my task manager and killing the process?

### ISSUE THREAD

**Issue by TyrantRC** [AriaMoradi/Tachidesk#890]
title.

I sometimes get a tray icon from where I can shutdown the server (Windows 10), but it's not reliable. If I shutdown the server and then I start it again, the icon will not appear sometimes.

I sometimes have to go into settings, disable the "Show icon in system tray" setting and reenable it in order to force the tray icon to appear. But this method sometimes leads to suwayomi staying online because I need to manually check if it's on or not.

So I was wondering if there was a button or something in the webclient I haven't seen yet.

Not sure if I should just make a bug report tbh.

**Comment by Syer10** [comment]
You could enable debug logs and that should make a console window pop up when the server is running. Then you can `CTRL + C` on the window whenever you want to kill the server

**Comment by TyrantRC** [comment]
thank you, that actually would help a lot. 
Except I cannot find how to enable "debug logging", I enabled it from the Java UI
![](https://i.imgur.com/GWcO5V5.jpeg)

I enabled it from the web UI
![](https://i.imgur.com/YRgj50o.jpeg)

I restarted multiple times and **I haven't gotten any console popping up**

I tried enabling it from the data folder [as explained here](https://github.com/Suwayomi/Suwayomi-Server/wiki/Configuring-Tachidesk-Server) but it was already set to true, nothing changed
![](https://i.imgur.com/JErv2zA.jpeg)

This feels like a permission issue from my side, any advice?
these are my folders:
client folder= I:\Portable Software\Suwayomi-Server-v1.0.0-r1498-windows-x64
data folder= I:\Software (I)\Suwayomi
download folder = E:\Images\Manga\\.Suwayomi

**Comment by AbandonedCart** [comment]
If you are using the newest release, the system tray option needs to be toggled off and back on if you have configured any folders. There appears to be a separate issue where configuring folders or using the launcher causes the system tray icon to be disabled regardless of its setting. It seems to be an issue with the settings, not your system.

Edit: I think your bug is more that the system tray icon is inconsistent than really looking for a workaround to force some sort of unintentional console window to allow you to crash the server.

**Comment by TyrantRC** [comment]
I decided to make 2 different issues with more information since this was just a question thread originally.
https://github.com/Suwayomi/Suwayomi-Server/issues/892
https://github.com/Suwayomi/Suwayomi-Server/issues/893
