### ISSUE TITLE
[Feature Request] Restore tracking information through backups

### ISSUE THREAD

**Issue by xdeiimoss** [AriaMoradi/Tachidesk#931]
## What feature should be added to Suwayomi?
The option to restore tracking information through backups.

##  Why/Project's Benefit/Existing Problem
Easier way to keep tracking information on both platforms without having to add the tracking to each entry manually on the secondary platform.

**Comment by taos15** [comment]
Are you asking to be able to restore outside tracking history (like anilist), or local tracking?

**Comment by xdeiimoss** [comment]
I'm not sure about what you mean by that... sorry.

I'll try to explain a bit more: If you use multiple apps (example: Mihon, TachiyomiJ2K, TachiyomiSY) you're able to restore the tracking information between them (which is an option when creating backups). That's what I want to be able to do with Suwayomi as well, without having to do it manually with every single title. 
![image](https://github.com/Suwayomi/Suwayomi-Server/assets/157998949/4057371c-5184-4b65-93c0-fab2b89d9b3e)
![Screenshot_20240413_152454_Mihon](https://github.com/Suwayomi/Suwayomi-Server/assets/157998949/13da36d1-df65-4fcb-9d7f-edb215de54f0)

**Comment by taos15** [comment]
So yes, you are talking about trackers's history (anilist, mangaupdates), not the local read history. So if I understand correctly, you are asking to store trackers' login info in a backup, (in mihon you have to select the option, backup credentials) because the tracking information itself get pulled from the tracker site. I just want to clarify what you are asking. If the backup has you credentials (you would assume the risk it implies to storage your credentials in that file), it should be able to automatically logged in. Another approach could be to just backed the Id on that manga for that tracker, it would have to still login in the tracker, but the manga will fetch the tracking automatically.

**Comment by xdeiimoss** [comment]
That's exactly what happens on the apps.
If I don't mark the option for tracker login tokens, It'll still have the tracking information from every entry, but it is only able to display them once you actually log into the trackers.

**Comment by schroda** [comment]
done with #940
